### ISSUE TITLE
vscode黑屏

### ISSUE THREAD

**Issue by FLQ77** [CharlesZhang6/vscode-live2d#10]
安装插件之后，提示重启vscode，重启后vscode编辑器只剩看板娘了，其他的全是黑屏,代码操作栏什么都看不到

**Comment by iCharlesZ** [comment]
vscode是什么版本？重启过后问题还在吗？

**Comment by FLQ77** [comment]
vscode的版本不确定，大概率是最新版，重启之后没有解决问题，电脑重启也没解决。最后卸载重装vscode,现在插件正常能用，重装后版本是1.50.1，应该是vscode的问题
