### ISSUE TITLE
能不能翻译成Javascript？

### ISSUE THREAD

**Issue by FurryR** [CharlesZhang6/vscode-live2d#12]
前排学习 可惜看不懂Typescript 能不能翻译一下

**Comment by iCharlesZ** [comment]
vscode会自己转成js的，你在  C:\Users\{username}\\.vscode\extensions\charlesz.vscode-live2d-1.7.200  这个目录下面可以看到

**Comment by iCharlesZ** [comment]
C:\Users\{username}\.vscode\extensions\charlesz.vscode-live2d-1.7.200

**Comment by FurryR** [comment]
感谢！
