### ISSUE TITLE
配置了"vscode-live2d.enabled": false，还是卸载不了

### ISSUE THREAD

**Issue by evatxu** [CharlesZhang6/vscode-live2d#13]
```js 
"vscode-live2d.enabled": false,
```
配置里加了 这个卸载了 也还是在

**Comment by iCharlesZ** [comment]
在卸载之前配置哦，如果不行试试在配置面板里面把第一个选项取消勾选

**Comment by iCharlesZ** [comment]
![enable](https://user-images.githubusercontent.com/16189913/103184383-e5d29200-48f2-11eb-9af2-faea06c87b49.jpg)

你是这样写的吗

**Comment by evatxu** [comment]
![image](https://user-images.githubusercontent.com/20672918/103205354-51891f00-4934-11eb-8f0c-baf181a43d3b.png)
配的应该对了，不知道为啥卸不掉

**Comment by iCharlesZ** [comment]
你步骤不对啊，这行都灰了，这样不会生效的。

另一个简单的方法是你在扩展面板里把看板娘配置的第一个选项取消勾选

**Comment by iCharlesZ** [comment]
> 如果安装了node.js环境，在卸载扩展后一段时候内会执行自动清理删除残留的样式。
如果没有安装node.js环境，则卸载前需要手动在设置里将看板娘设置成关闭。或者在 settings.json 中设置 {"vscode-live2d.enabled": false}，然后再卸载插件。如果直接删除插件会有遗留。
>> tips: 如果找不到设置面板在哪，可点击左下角 “齿轮——设置” 打开设置面板(确保活动栏: activity bar是打开状态)，然后搜索 "@ext:charlesz.vscode-live2d" 即可看到vscode-live2d设置选项。
或者点击左边活动栏(activity bar)中的扩展(extension)找到vscode-live2d，点击右下角的小齿轮选择扩展设置也能直接进入设置选项。

**Comment by evatxu** [comment]
> 另一个简单的方法是你在扩展面板里把看板娘配置的第一个选项取消勾选
