### ISSUE TITLE
1.53.0-insider 不正常工作

### ISSUE THREAD

**Issue by Henry-ZHR** [CharlesZhang6/vscode-live2d#14]
VSCode 版本
```text
版本: 1.53.0-insider (user setup)
提交: ed6c343edb720d91ee0859e566c84b5687f5a9d5
日期: 2021-01-08T10:46:04.327Z
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Windows_NT x64 10.0.21286
```

---

还没加载好时：

![](https://user-images.githubusercontent.com/51886614/104094914-d5e18780-52ce-11eb-91c4-8d17a4673411.png)

加载好之后看板娘并没有出现，紫色的框也消失了

---

[控制台日志](https://github.com/iCharlesZ/vscode-live2d/files/5791267/-1610203731033.log)

不启用时没有那些错误，所以我觉得应该有关系

**Comment by iCharlesZ** [comment]
我看了下Insiders版本确实会存在这个问题，初步判断是Live2D的问题，我会尝试着解决这个问题

**Comment by iCharlesZ** [comment]
v1.8.0已修复，可以试试最新版
