### ISSUE TITLE
vs code更新到1.53.0之后看板娘无法使用

### ISSUE THREAD

**Issue by CarefulDeveloper** [CharlesZhang6/vscode-live2d#16]
如题，当我把vs code1.52安装包安装后解决此问题。希望作者能修复这个看板娘不能在新版本vs code运行的问题

**Comment by v587long** [comment]
需要手工修改workbench文件

**Comment by CarefulDeveloper** [comment]
> 需要手工修改workbench文件

...\Microsoft VS Code\resources\app\out\vs\workbench目录下的文件吗? 怎么修改? 谢谢

**Comment by v587long** [comment]
https://my.oschina.net/u/4161755/blog/4775153  你可以参考一下这个文章 修改完之后有几率会出现2个模型 再换回原来的文件 就能正常加载了 反正我是弄了很久 感觉是这个的问题

**Comment by CarefulDeveloper** [comment]
> https://my.oschina.net/u/4161755/blog/4775153 你可以参考一下这个文章 修改完之后有几率会出现2个模型 再换回原来的文件 就能正常加载了 反正我是弄了很久 感觉是这个的问题

感谢回答，这篇文章对我帮助很大，我是直接将1.52(live2d可以正常运行)的workbench.html文件备份,然后升级到1.53,然后再将workbench.html还原就成功了!

**Comment by shijizhang** [comment]
macOS
.../Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html 
Windows
...\Microsoft VS Code\resources\app\out\vs\code\electron-browser\workbench\workbench.html
中将以下代码注释掉(即1.53.0之后新增的代码):
`<meta http-equiv="Content-Security-Policy" content="require-trusted-types-for 'script'; trusted-types TrustedFunctionWorkaround ExtensionScripts amdLoader cellRendererEditorText defaultWorkerFactory diffEditorWidget editorGhostText domLineBreaksComputer editorViewLayer diffReview extensionHostWorker insane notebookRenderer safeInnerHtml standaloneColorizer tokenizeToString webNestedWorkerExtensionHost;">`
重启vscode生效

**Comment by iCharlesZ** [comment]
新版本 v1.8.1 已发布，需使用 vscode 1.70.1 以上版本。

**Comment by wumian233333** [comment]
啊啊！你这插件直接把我vsc干黑屏了，就是好奇点一下，没想到直接黑屏了，重启也黑屏
