### ISSUE TITLE
I can't apply vscode-live2d on VS code in 1.53

### ISSUE THREAD

**Issue by CarefulDeveloper** [CharlesZhang6/vscode-live2d#17]
Issue Type: <b>Bug</b>

If I update vs code from 1.52 to 1.53, I can't apply this extension.

Extension version: 1.7.200
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600U with Radeon Graphics          (12 x 2096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.37GB (9.74GB free)|
|Process Argv|--crash-reporter-id a235a2c9-35a9-4ba2-9e96-cb7438b1d462|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by iCharlesZ** [comment]
v1.8.0 has been fixed, you can install the latest version.
