### ISSUE TITLE
突然不能显示了

### ISSUE THREAD

**Issue by lilongcnc** [CharlesZhang6/vscode-live2d#18]
VSCode 1.2.52不知道怎么就不能显示了，卸载vs重装也不行，家里电脑就可以，setting里边设置了显示了，不知道怎么搞的就是不显示，右下角那一块压根就没有连空白占位也没有。有朋友遇到相同问题吗？

**Comment by iCharlesZ** [comment]
v1.8.0已修复，可以试试最新版
