### ISSUE TITLE
卸载不了，属于是醉了

### ISSUE THREAD

**Issue by lty12b9b0a1** [CharlesZhang6/vscode-live2d#25]
下下来之后玩了一会想卸载了，第一次没注意那么多直接卸载。好家伙从这之后再也卸载不掉了，设置里关闭什么的都试过了，把vscode的各种缓存文件和extension文件都扒了一遍，能删的和都删了。重启code，好家伙，还在。尝试过重新下回来，然后settings里关闭，禁用，再卸载。然而并没有什么卵用。折腾了2个小时了，准备重装vscode了，服。

**Comment by iCharlesZ** [comment]
遇到问题请先查看 `README.md`

**Comment by rugbbyli** [comment]
> 下下来之后玩了一会想卸载了，第一次没注意那么多直接卸载。好家伙从这之后再也卸载不掉了，设置里关闭什么的都试过了，把vscode的各种缓存文件和extension文件都扒了一遍，能删的和都删了。重启code，好家伙，还在。尝试过重新下回来，然后settings里关闭，禁用，再卸载。然而并没有什么卵用。折腾了2个小时了，准备重装vscode了，服。

一毛一样……
