### ISSUE TITLE
ts文件开头报错

### ISSUE THREAD

**Issue by bosswnx** [CharlesZhang6/vscode-live2d#30]
我们想根据您的代码进行二次开发，但是clone了您的代码之后发现编译有报错，每一个文件的开头都会报一个莫名其妙的错误，无论开头是什么：
![1](https://user-images.githubusercontent.com/45135497/166109444-576de864-cb21-4d10-8320-7d42c083a1b0.png)
请问有什么解决的办法吗？谢谢！

**Comment by iCharlesZ** [comment]
你本地编辑器设置了什么eslint规则吧

**Comment by bosswnx** [comment]
已收到，谢谢。
