### ISSUE TITLE
New version of VSCode breaks the extension

### ISSUE THREAD

**Issue by ghost** [CharlesZhang6/vscode-live2d#31]
It look like the new version of vscode remove the `workbench` folder in `%localappdata%\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-browser`

I open the developer tool and see that the extension can not find the workbench.js

VSCode version

```
Version: 1.70.0 (user setup)
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:16.462Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by ghost** [comment]
It was moved to `resources\app\out\vs\code\electron-sandbox\workbench`

https://stackoverflow.com/a/73300839/4015729

**Comment by iCharlesZ** [comment]
Thanks for the feedback. The new version v1.8.1 has been released.
