### ISSUE TITLE
更新后模糊的完全没办法看...  回退了🙁

### ISSUE THREAD

**Issue by CrazyChenzi** [CharlesZhang6/vscode-live2d#4]

**Comment by iCharlesZ** [comment]
请问是哪个版本模糊？你设置了改变看板娘大小吗？
最新版1.3.0还有模糊的情况吗？

**Comment by CrazyChenzi** [comment]
![image](https://user-images.githubusercontent.com/26319882/88797868-9585c580-d1d6-11ea-8262-1888a3c0975e.png)
1.1.1 版本过后就很模糊...

**Comment by iCharlesZ** [comment]
你在设置里尝试提高下宽高呢？还是模糊吗？

**Comment by CrazyChenzi** [comment]
![image](https://user-images.githubusercontent.com/26319882/88798070-e4cbf600-d1d6-11ea-8ea4-888af64cb6a9.png)

**Comment by iCharlesZ** [comment]
你是Mac还是windows

**Comment by CrazyChenzi** [comment]
一样的呢，1.1.1版本ok

**Comment by CrazyChenzi** [comment]
windows  我自己改了下1.1.1版本的样式😂
看了了1.1.1之后代码，没发现改了啥...就很莫名其妙的模糊了

**Comment by iCharlesZ** [comment]
你这个model url可以发我试试吗，我查查什么原因

**Comment by CrazyChenzi** [comment]
[live2d_models_collection](https://github.com/xiaoski/live2d_models_collection)
kanzaki

**Comment by iCharlesZ** [comment]
你是把模型下载到本地加载的吗

**Comment by iCharlesZ** [comment]
![temp](https://user-images.githubusercontent.com/16189913/88804111-0c738c00-d1e0-11ea-9dd3-eb26a2b37e49.png)
呃，我试了下还挺清晰的，你有修改什么文件参数吗？我有点想知道你是怎么操作的

**Comment by CrazyChenzi** [comment]
加载的github的raw，就修改了宽高啊
