### ISSUE TITLE
Did you have any problem publishing it?

### ISSUE THREAD

**Issue by AllanOricil** [CharlesZhang6/vscode-live2d#6]
Im asking it because it seems you edit the vscode source code. Very creative. Thanks for sharing that!
But didn't they analysed your code after publishing it?

**Comment by iCharlesZ** [comment]
This is a VSCode extension.
Did you mean VSCode Marketplace? https://marketplace.visualstudio.com/items?itemName=CharlesZ.vscode-live2d
